import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>The Earth Protocol</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <nav>
        <div className="px-52">
          <div className="flex justify-between">
            <div className="flex space-x-4">
              <div>
                <a href="#" className="flex items-center py-5 px-2 text-white ">
                  <Image
                    src="/logo.svg"
                    alt=""
                    width={24}
                    height={24}
                    className="items-center"
                  />
                  <span className="font-bold">The Earth Protocol</span>
                </a>
              </div>
            </div>
          </div>
        </div>
      </nav>
      <section>
        <div className="bg-black text-white py-20">
          <div className="container mx-auto flex flex-col md:flex-row items-center my-12 md:my-24">
            <div className="flex flex-col w-full lg:w-1/3 justify-center items-start p-8">
              <h1 className="text-3xl md:text-5xl text-green-300 tracking-loose">
                The Earth Protocol
              </h1>
              <h2 className="text-3xl md:text-5xl leading-relaxed md:leading-snug mb-2">
                Track your digital impact
              </h2>
              <p className="text-sm md:text-base text-gray-50 mb-4">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
              <a
                href="#"
                className="bg-transparent hover:bg-green-300 text-green-300 hover:text-black rounded shadow hover:shadow-lg py-2 px-4 border border-green-300 hover:border-transparent"
              >
                Read more
              </a>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
